[global]
timeout = '10s'
strategy = 'all'
log_level = 'error'

[[chains]]
id = 'stargate'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9092'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'node_key'
store_prefix = 'stargate'
gas = 3000000
fee_denom = 'stake'
fee_amount = 10
clock_drift = '5s'
trusting_period = '14days'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[[chains]]
id = 'h3liax'
rpc_addr = 'http://localhost:26357'
grpc_addr = 'http://localhost:9091'
websocket_addr = 'ws://localhost:26357/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'node_key'
store_prefix = 'heliax'
gas = 3000000
fee_denom = 'stake'
fee_amount = 10
clock_drift = '5s'
trusting_period = '14days'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[[connections]]
a_chain = 'stargate'
b_chain = 'h3liax'
delay = '10s'

[[connections.paths]]
a_port = 'transfer'
b_port = 'transfer'

[[connections]]
a_chain = 'stargate'
b_chain = 'h3liax'
delay = '10s'

[[connections.paths]]
a_port = 'transfer'
b_port = 'transfer'